### ISSUE TITLE
博客中不能评论，还好这里可以，看到阳光了。

### ISSUE THREAD

**Issue by ghost** [lawrence-working-group/network-cookbook#5]
我从某篇文章中知道了您的博客，看了 SRX300 家用路由器配置后，感觉可以买个玩玩。于是在淘宝商家买了个全新的。结果发现下载固件还要注册账号，注册了，竟然还要人工审核，过了 24 小时没反应，于是电联，juniper 办事处的人打电话过来人工审核，我告诉他们是家庭使用的，结果直接被拒。求求大佬帮我下载两个固件，不胜感激。

https://webdownload.juniper.net/swdl/dl/secure/site/1/record/142054.html?pf=SRX300
https://webdownload.juniper.net/swdl/dl/secure/site/1/record/142146.html?pf=SRX300

麻烦您传到我的 Dropbox 
https://www.dropbox.com/request/ed7m4KkTyKaTwKPgerWq

**Comment by Jamesits** [comment]
企业产品千万不要有这种买个玩玩的心态，技术支持，资料，固件下载都会成为问题。除非你打算以后做这一行……

**Comment by ghost** [comment]
根据您的教程，恢复出厂后，无法用 SSH 空密码登陆，只能在 J-WEB 中先完成设置向导，这样会生成一些默认的配置，于是您的命令也无法正常提交了。
不过通过自己的研究，通过 J-WEB 搞定了 PPPoE iPv4 拨号，能上网了其它再慢慢琢磨。
希望大佬可以多出点家用用途的教程，让我等菜鸟沾沾光，比如 DDNS 。
